### ISSUE TITLE
Realtime client side validation doesn't work with schema with 2+ refinements

### ISSUE THREAD

**Issue by ThatRex** [ciscoheat/sveltekit-superforms#110]
**Description**
Realtime client side validation doesn't work with schema with 2+ refinements

**Example**
https://github.com/ThatRex/superforms-test/tree/master/src/routes/superform-b

**Comment by rburgst** [comment]
note that the same happens when you use 
```typescript
export const schema = z.object({
	name: z.string().min(1),
	email: z.string().email(),
 // the z.optional causes a problem
	items: z.optional(z.array(z.object({ title: z.string(), name: z.string().min(3) })))
});

```

see https://stackblitz.com/edit/sveltekit-superforms-testing-3pajxe

**Comment by ciscoheat** [comment]
Both of these should work now with 0.8.3, please check it out!

**Comment by ThatRex** [comment]
Thanks! Just updated and this problem is fixed.

There is some weird behavior however as seen in this [example](https://github.com/ThatRex/superforms-test/tree/master/src/routes/superform-c) where name 1 and 2 should match.
![image](https://user-images.githubusercontent.com/48845898/234643868-1ca7ecaf-5360-4a16-b991-8b9dd21bdfc8.png)

**Steps To Reproduce:**
1. Taint Name 2
2. Set Name 1 to a non matching name. (Error gets added to name2)
3. Set Name 1 to a matching name. (Error does not get removed from name2)

**Comment by ciscoheat** [comment]
Yes, the updating of the data was missing during side effects. Thanks, there will be another patch soon.

**Comment by ciscoheat** [comment]
It was a multi-faceted problem, there is some timing issue with select fields and `bind:value`, so the bindings are triggered in a different compared to the events. But v0.8.4 is released, this should be fixed.

The only thing that cannot be fixed is if you, in this example, change name 1 and expect to see the error message. This doesn't work since field 2 isn't tainted, and that's where the error is. Otherwise all seemingly unrelated fields would have errors set on them.

**Comment by ThatRex** [comment]
Cool, Thanks! Just updated, tested and cant find any further issues.
