### ISSUE TITLE
Component form data is persisted when it shouldn't

### ISSUE THREAD

**Issue by ciscoheat** [ciscoheat/sveltekit-superforms#164]
Forwarded from https://discord.com/channels/1088090866649939990/1111218174474600458

**Description**
I have a form in a separate component. On the page, that component is conditionally hidden so I can switch between an edit mode and a view mode, without leaving the page. When you leave edit mode, the form is supposed to be reset to the initial values that it was loaded with (by calling reset()).

The problem I'm running into is when the form component is hidden, its initial values get set to the current values. So on subsequent attempts to edit the form and then rehide it, calling reset() sets the values back to what they were on the first hide instead of the initial values that the page was loaded with.

Also, in my actual implementation I wanted to have the form hide/show based on a search param (eg. ?edit). If I I do a goto()  to set/remove the search param, this bug still occurs, even if I don't have the form setup directly in the +page and not in a separate component.

**If applicable, a MRE**
I've created an example to demonstrate this behavior here: https://www.sveltelab.dev/njk44xnae1kotvk. Click Edit, then change one of the fields, click Close Edit and then click Edit again. The form will now show the changes you made instead of the initial values that it loaded with.

**Comment by ciscoheat** [comment]
An additional MRE for this issue: https://www.sveltelab.dev/f32m9qfkqksor9q

**Comment by stv8** [comment]
I found another similar issue, I noticed that form repopulates (and `onUpdated` is called again) when the form is completely mounted and remounted. However if you just goggle the css visibility the issue doesn't happen. 

https://www.sveltelab.dev/8vdbe7ems9xoy5l

**Comment by hmnd** [comment]
I've narrowed this issue down to the rebind that happens [here](https://github.com/ciscoheat/sveltekit-superforms/blob/b65f8e56b4a089b330b263787708600ac82908d9/src/lib/client/index.ts#L803-L808). What I don't understand is how the page store could possibly be getting the form's current data...

**Comment by imsam** [comment]
Not sure how helpful it is, but I'm seeing similar issues to those described above, without using any components.

I have a superform being rendered on a +page.svelte page with an "edit" mode, and am seeing inconsistently that some fields appear to be updating data.fieldName instead of just the $form store.

In my case, cancelling out of "edit" mode replaces the input fields with regular <p> tags showing the original data.fieldName values. When my page first loads, it's loading into read-only mode, showing the correct values in <p> tags. Sometimes, the original data.fieldName values have been replaced by the value I set in the input field (which is only bound to $form.fieldName when toggling from edit mode back to read-only mode.

Very strange, and I can't offer much more insight into the cause at the moment, but this _feels_ like the data object that's being returned by +page.server.ts (or +page.ts) is being updated by superforms, even when nothing is being posted.

**Comment by ciscoheat** [comment]
Another example that shows the "fail to reset" behavior: https://stackblitz.com/edit/sveltekit-superforms-1-testing-amudgw?file=src%2Froutes%2F%2Bpage.svelte,src%2Froutes%2FForm.svelte

**Comment by ivenuss** [comment]
fyi: attaching description to mention demo above ☝️ 

### Expected behavior
After unmounting and `reset`ting the form component (by clicking on "Cancel" button) with inputted data I would expect that form will get empty after another mounting with **Toggle** button.

Instead of this expected behavior the data will remain inside the form. 

### What I want to achieve?
I would like to clear all data in form when `Cancel` button is pressed.

**Comment by ciscoheat** [comment]
Finally fixed this annoying issue! Will release v1.3.0 soon with the fix.

**Comment by stv8** [comment]
Awesome!!! I'll update to the version when it's released and let you verify it

**Comment by ciscoheat** [comment]
It's released now!
