### ISSUE TITLE
offer onReset() hook

### ISSUE THREAD

**Issue by xmlking** [ciscoheat/sveltekit-superforms#180]
I am using 3rd party `Tags` Input component that is  bind to `$form.rule.tags`. 
It  messing with `Tainted` state when form is reset using `reset()` function from `superform`. 
It would be nice if there is a lifecycle event hook  e.g., `onReset()` that get triggered after reset, so  can add custom logic to untaint manually i.e.,  `$tainted = undefined;` 
<img width="321" alt="image" src="https://github.com/ciscoheat/sveltekit-superforms/assets/627951/e21c39f8-da5b-45f1-8e3e-b7f15170193c">

To reproduce: https://github.com/xmlking/svelte-starter-kit/tree/main/src/routes/(app)/dashboard/policies/%5Bid%5D

**Comment by ciscoheat** [comment]
Is it possible to apply the custom logic at the point where you call reset?

**Comment by xmlking** [comment]
Yes I can. I did little over design componentizing `Form` reusable component  with builtin reset button :(

I was thing it might be useful  to offer  `onReseted` hook like you have `onUpdated`   in [events](https://superforms.vercel.app/concepts/events) docs.

**Comment by ciscoheat** [comment]
Ok, good to hear that, I was asking because I'm not a big fan of arbitrary events, they work much like a 21:th century GOTO. In comparison, the submit events are all connected in a chain. So I'm hesitant to add any more events. There are two other events I'm considering in #137, but still, not certain, and nobody's asked for them, so they are in the icebox. :)

**Comment by xmlking** [comment]
Agree custom reset functionality is app developer’s concern. They could hook custom logic pre/post from reset by superform provided reset() function
