### ISSUE TITLE
A way to validate form and add errors to the error store on the client

### ISSUE THREAD

**Issue by douglasward** [ciscoheat/sveltekit-superforms#185]
**Is your feature request related to a problem? Please describe.**
There seems to be no way to easily validate the form on the client with the zod schema and add the errors to the existing error store. There is the superValidate method and the validate method but neither of them update the existing form stores and thus no errors are shown by default. We currently need to run the validation on the client as we need to run the graphql mutation on the client so that we can use optimistic responses and update the client cache. 

**Describe the solution you'd like**
When calling superValidate on the client it should update the existing stores with the relevant values like what happens if it is run on the server. E.g. errors are added to the error store.

**Describe alternatives you've considered**
Updating the stores manualy using `errors.set(newErrors)` for example.

**Comment by ciscoheat** [comment]
Hi, the state management in a superForm is quite complicated, so it's tricky just updating it based on the data that `superValidate` returns. You can see `superValidate` as returning a validation structure that can be input to the constructor of a new superForm.

A few options, since you need to run it on the client:

1. Use [SPA mode](https://superforms.rocks/concepts/spa) and an event like `onUpdate` to modify the validation result before it's updated.

2. Call `validate` with no options and it will return basically what `superValidate` would do if the form was posted. Then you can modify it, and use `restore` (which is used with [snapshots](https://superforms.rocks/concepts/snapshots) usually), adding an extra field for `tainted`:

```ts
const { form, validate, restore, ... } = superForm(data.form)

const validated = validate()

// Modify validated here

restore({ ...validated, tainted: undefined })
```

**Comment by ciscoheat** [comment]
Did any of these solutions solve the problem?

**Comment by VitAndrGuid** [comment]
Not the person who opened the PR, but i had the same problem and option 2 solved it.

Adding a little bit of more context, i have a login form to a external api that responds with a set-cookie header, therefore the request to the external api needed to be sent on the client side after the form validation for the cookie to be set, also `validationMethod: 'oninput'` was not desired.

option 2 solved it fine, but would there be a even better solution ?

nevertheless this lib is awesome, thanks.

**Comment by ciscoheat** [comment]
Thank you. :) In general, I recommend the [SPA approach](https://superforms.rocks/concepts/spa) when calling an external API, it keeps things together a bit better with the event chain. 

So in `onUpdate` you call the external API (with await), make the necessary changes to the `form` parameter, and the stores will be automatically updated when the function returns.

**Comment by douglasward** [comment]
Sorry, yes, using SPA mode has certainly cleaned up cancelling requests to the server etc, but I'm not sure what you mean by "modifying the validation result before it is updated". Would you be able to give a quick example of what this could look like?

**Comment by ciscoheat** [comment]
It means that you can modify the `form` parameter in onUpdate. An example is here: https://superforms.rocks/concepts/spa#displaying-the-form but it's not limited to the helper functions.
