### ISSUE TITLE
Support strict mode for schemas

### ISSUE THREAD

**Issue by ciscoheat** [ciscoheat/sveltekit-superforms#217]
Should it be possible to set strict mode for a schema and that superValidate throws an exception (or rather, passes on the Zod exception)?

The same if strict is set for a field within the schema?

**Comment by ciscoheat** [comment]
This could be a breaking change, since adding strict to a schema currently does nothing, so it has to wait.

**Comment by alexbjorlig** [comment]
Hi @ciscoheat  - trying to migrate some GraphQl mutations to Sveltekit superforms and this issue came up when integration testing.

GraphQl does not allow "extra" fields, but with Superforms/Zod, the schema is valid --> even if I provide `.strict`.

Is there a workaround until this feature is upgraded :) ?

**Comment by ciscoheat** [comment]
Hi, maybe you can use `Object.keys(schema.shape)` to get the keys, and filter based on that. If there are effects on the schema, you have to unwrap it first, which you can do [like this](https://github.com/ciscoheat/sveltekit-superforms/blob/1622b112c6f27d2d9a521beb2fa2b51f636b4b5d/src/lib/schemaEntity.ts#L87C1-L129).
