### ISSUE TITLE
Leave Page Confirmation is showing for empty form with select

### ISSUE THREAD

**Issue by Zerotask** [ciscoheat/sveltekit-superforms#249]
- [x] Before posting an issue, read the FAQ at https://superforms.rocks/faq and search the previous issues.

**Description**
I'm using use:enhance and have a form with 2 select. I noticed, that when I don't input anything and don't select anything, the leave page confirmation pops up if I try to navigate to another page.
This should only show up, if I input/select something.

If I debug it, the values of those 2 selects are undefined at first and then immediately jump to an empty string.

In Stackblitz, when I tried to reproduce it, the value of the select was always the first option.

In my case I'm using Flowbite Svelte which has a disabled option at the beginning (to show a text like `Choose an option`).

In every case, I did not select something and therefore I shouldn't see a confirmation if I leave a page where I did not change anything.

**Comment by ciscoheat** [comment]
Maybe that should be a FAQ question. If you don't have a valid option set, it will be modified like that, but it also depends on your schema field. If it's optional, the form will be tainted since the value changes. You can either set its default value to an empty string, or use a [stringProxy](https://superforms.rocks/api#stringproxyform-fieldname-options) to force it to be undefined or null when empty.

**Comment by Zerotask** [comment]
Both selects are required in my schema and I don't want to have a default. I want my users to actually select an option.

my 2 selects are type and address.country. Both are empty

I'm using a nativeEnum
```ts
type: z.nativeEnum(TypeEnum),
```

This is my debug:
![image](https://github.com/ciscoheat/sveltekit-superforms/assets/20150243/7ac0d2bf-ee84-4eb4-b54d-e1349b84524c)

So I'd assume, since type and address.country are empty, that no confirmation should be shown.

**Comment by ciscoheat** [comment]
Setting a default and requiring a value is not the same thing. It needs to have a default empty string, since that's the value for an empty select option. You can do it like this: https://superforms.rocks/default-values#changing-a-default-value with an empty string. If it doesn't work, make an [MRE](https://stackblitz.com/edit/sveltekit-superforms-1-testing?file=src%2Froutes%2F%2Bpage.server.ts,src%2Froutes%2F%2Bpage.svelte) at Stackblitz and I'll take a closer look.

**Comment by Zerotask** [comment]
> Setting a default and requiring a value is not the same thing.

Yes. I didn't say something else. Both selects are required and both selects should not have a default value => user must choose something.

> It needs to have a default empty string, since that's the value for an empty select option. You can do it like this: 

Thank you, that's working. Although it shows me an error im my IDE

> No overload matches this call.
  Overload 1 of 2, '(def: TypeEnum): ZodDefault<ZodNativeEnum<typeof TypeEnum>>', gave the following error.
    Argument of type '""' is not assignable to parameter of type 'TypeEnum'.
  Overload 2 of 2, '(def: () => TypeEnum): ZodDefault<ZodNativeEnum<typeof TypeEnum>>', gave the following error.
    Argument of type 'string' is not assignable to parameter of type '() => TypeEnum'.

```ts
type: z.nativeEnum(TypeEnum).default(''),
```

**Comment by ciscoheat** [comment]
Cast the empty string to TypeEnum, it's unavoidable for these cases.

**Comment by ciscoheat** [comment]
Added this to the FAQ, so I'm closing this now.
