### ISSUE TITLE
[TS] Pre-defined types do not work properly: `z.object<Type>({})`

### ISSUE THREAD

**Issue by protibimbok** [ciscoheat/sveltekit-superforms#252]
- [x] Before posting an issue, read the FAQ at https://superforms.rocks/faq and search the previous issues.

**Description**
Typescript complains about the error messages for array field when z.object is defined with type.
In `+page.server.ts`
```typescript
type FormType = {
    name: any;
    email: any;
    days: any;
};

const schema = z.object<FormType>({
    name: z.string().min(1),
    email: z.string().email(),
    days: z.number().min(0).max(6).array().nonempty()
});
```

Now, in `+page.svelte`:
```html
<script lang="ts">
  import { superForm } from "sveltekit-superforms/client";
  export let data;
  const { form, errors, message, constraints, enhance } = superForm(data.form);
</script>
<p class="invalid">{$errors.days?._errors || "No error"}</p>
<!--Form and other stuff is omitted for clarity of the problem-->
```
This should work fine (it does) but the ide complains about `_errors` not existing:
![image](https://github.com/ciscoheat/sveltekit-superforms/assets/33311165/78f20800-3f12-4224-beb6-69b302d6c26f)

> Also, the name `_errors` does not feel right, as `_` is used to indicate private properties.

https://stackblitz.com/edit/sveltekit-superforms-1-testing-rjkewk?file=src%2Froutes%2F%2Bpage.svelte

**Comment by ciscoheat** [comment]
Using a type parameter for `z.object` works most of the time, unless the type is `any`, which makes the inference for arrays fail. In your case, you must specify `FormType` as:

```ts
type FormType = {
  // This works, since `_errors` is not used
  name: any; 
  // This works, since `_errors` is not used
  email: any;
  // For arrays, you must use ZodArray in the type.
  days: z.ZodArray<z.ZodNumber, 'atleastone'>;
};
```

Since using `any` isn't recommended, this won't be fixed, and it's probably best to let typescript infer the raw schema types anyway.

> Also, the name _errors does not feel right, as _ is used to indicate private properties.

It's not an oversight, it's how Zod does it, to avoid collisions between property names and validation errors. It's kind of a private property, or at least another aspect of the object, so it makes sense.
