### ISSUE TITLE
Input fields are cleared when JS finished loading

### ISSUE THREAD

**Issue by Gerschtli** [ciscoheat/sveltekit-superforms#258]
- [x] Before posting an issue, read the FAQ at https://superforms.rocks/faq and search the previous issues.

**Description**

When the internet speed is fairly slow, JS is enabled and the user types in text into input fields, these values get reset as soon as the JS finished loading.

See the following screenshot of the final loading state when entering "test" into both input fields as soon as they were interactable while setting throttling to "Fast 3G".

![Screenshot from 2023-08-29 16-29-24](https://github.com/ciscoheat/sveltekit-superforms/assets/10353047/633861c8-e42e-4685-a1ce-31b52cb6a79b)

**If applicable, a MRE**

I created https://github.com/Gerschtli/superforms-bug-input-values-reset-on-load to reproduce the issue (on stackblitz it was not reproducible).

1. Run `pnpm install`
1. Run `pnpm dev -- --open`
1. On the page execute the described steps:
    1. Load this page with "Fast 3G" or similar
    1. Enter some values into both inputs immediately
    1. Wait for JS to be loaded completely and notice how the first input value is cleared (see also `console.log` statement)

**Comment by ciscoheat** [comment]
This is not a Superforms issue, but is more general; if you use `bind:value` with a normal variable, the same problem occurs.

**Comment by opack** [comment]
Hi! I am running into the exact same problem: in my tests, my form is reset after Playwright has already filled the values, and thus the subsequent `expect` fail because the form is reset at some point. If I add a pause, then everything is ok and the form is not reset. Here is a functioning test:
```typescript
test('when password is too short', async ({ page, pom: { password } }) => {
	// Form is reset if the following line is removed
	await page.waitForTimeout(1000)
	await password.fill('short')
	await password.blur()
	await expect(page.getByText('String must contain at least 6 character(s)')).toBeVisible()
})
```
I understand that this issue is not caused directly by Superforms, but I did not find a relevant issue in Svelte or SvelteKit repos (maybe I missed it :-\ ).
@Gerschtli You [said](https://github.com/ciscoheat/sveltekit-superforms/issues/258#issuecomment-1698829103) that you were going to move it to the svelte repo. Can you point me (and all the future people that will come here) to that very issue please, so that I can see what answer has been provided and maybe continue the discussion? Many thanks! 🙏

**Comment by opack** [comment]
To anyone passing by and wondering where this issue is, I finally found [it](https://github.com/sveltejs/svelte/issues?q=is%3Aissue+input+clear+load) 😄
