### ISSUE TITLE
Error on forms with redirect

### ISSUE THREAD

**Issue by stefandevo** [ciscoheat/sveltekit-superforms#26]
Hi,

I have a login form, where I use the superforms component.
When I execute the login action on the server, I do something like
`if (callResponse.requestId) throw redirect(302, '/auth/verify/' + callResponse.requestId);`
to go to a next page with a request id.

This works, however, I now see following error appearing:

`Uncaught (in promise) Error: No form data found in $page.data (PageData). Make sure you return { form } in the form actions and load function.`

Any idea what I should do...

**Comment by ciscoheat** [comment]
That must have been introduced with the [multiple forms](https://github.com/ciscoheat/sveltekit-superforms/wiki/FAQ#are-multiple-forms-on-the-same-page-supported) support. I'll try to release a fix later today.

**Comment by ciscoheat** [comment]
Are you redirecting in an endpoint or in a form action?

**Comment by stefandevo** [comment]
In a form action

**Comment by ciscoheat** [comment]
Great, it's fixed now in the latest version. If you'd been throwing a redirect in an endpoint it wouldn't work, since `superForm` expects an `ActionResult`. In that case you have to use the `actionResult` helper instead, [described here](https://github.com/ciscoheat/sveltekit-superforms/wiki/API-reference#actionresulttype-data-status).

**Comment by ciscoheat** [comment]
Is this working for you now?

**Comment by marcolinolucas** [comment]
Is there a way to use this using form actions? I need to redirect my user after submit but if I use this syntax I receive a non-POJOs error
