### ISSUE TITLE
Docs: Make it easier to find populating from database

### ISSUE THREAD

**Issue by oscarhermoso** [ciscoheat/sveltekit-superforms#271]
Firstly, thank you for SuperForms Andreas, has made building forms with SvelteKit very pleasant

As someone using the docs as a reference for an existing project, I had a lot of trouble finding this info (~20 minutes)

https://superforms.rocks/get-started#initializing-the-form-in-the-load-function

> 2. Populate from database
> If you want to populate the form, you can call a database and send the data to the form as the first parameter, schema second, like this:

```js
 export const load = async ({ params }) => {
  const user = db.users.findUnique({
    where: { id: params.id }
  });
  if (!user) throw error(404, 'Not found');
  const form = await superValidate(user, schema);
  // Always return { form } in load and form actions.
  return { form };
 };
```

Issues:

* It only exists under the "Get Started" page (If it is also on another page, I couldn't find it)
* "Populate" doesn't return search results. Ideally it would also return this heading: "Populate from database"
* This info should be duplicated in or linked from ["Default values"](https://superforms.rocks/default-values)
* Some JSDoc on hover on `superValidate()` would have also saved me

**Comment by ciscoheat** [comment]
I can change them to headlines which should make them indexed (they should anyway, but I don't have time to figure this out right now). 

I don't think they should be under Default values though, since that's about default schema values. Populating the form is another topic, it's already in the API [here](https://superforms.rocks/api#supervalidateschema--data-schema--options-options) and I don't know why that doesn't rank high in the search, and again no time to figure that out at the moment. That's why I'd also appreciate if you could add some JSDoc to the [superValidate](https://github.com/ciscoheat/sveltekit-superforms/blob/main/src/lib/superValidate.ts) function, that contribution would be worth a lot.

**Comment by ciscoheat** [comment]
Docs and search updated.
