### ISSUE TITLE
Support zod's `.catchall`

### ISSUE THREAD

**Issue by fehnomenal** [ciscoheat/sveltekit-superforms#289]
**Is your feature request related to a problem? Please describe.**
In my form the user is presented multiple groups of radio buttons and has to choose one option in each group.
The groups are dynamic and not known beforehand. In the end they don't matter and I'm only interested in the choices not to which group each choice belongs.

I tried to generate inputs with unique names per group with a common prefix (`name="id_{group_id}"`). But the schema cannot be validated as I do not know the keys to validate.
I used `.catchall` which does not work because `formDataToValidation` looks at the defined keys in the schema to extract them from the form data.

**Describe the solution you'd like**
`formDataToValidation` should take the schema from `.catchall` into account.

**Describe alternatives you've considered**
- Not use superforms for this form.
- Transfer the key names to the backend to build the schema dynamically.

**Comment by ciscoheat** [comment]
Dynamic behavior has always been a bit of problem for Superforms, since the schema is what defines the resulting data. But it sounds like you could use a Record or an array for what you want, which is supported. 

Here's information about arrays: https://superforms.rocks/concepts/nested-data#arrays-with-primitive-values

Here's an example for record: https://github.com/ciscoheat/sveltekit-superforms/tree/main/src/routes/record

**Comment by fehnomenal** [comment]
The array approach unfortunately doesn't work because the browser than treats all radio buttons in the same group and the user can select only a single one. Records seem to need `dataFormat: 'json'` which I tried to avoid.

What about the following:
After iterating over the known fields from the schema, all remaining fields are checked against the catchall schema (if provided).

In my tests this works, I will prepare a PR later.

**Comment by ciscoheat** [comment]
This could be working now in v2, since it uses the JSON schema [additionalProperties](https://www.learnjsonschema.com/2020-12/applicator/additionalproperties/) to check for extra keys now, which is added by the Zod adapter when you use catchall. Can you check it out and see if there's something else that needs to be done? Migration guide: https://superforms.rocks/migration-v2

**Comment by ciscoheat** [comment]
Found some issues with how it works now, so I'll do a proper test for it in the next alpha version.

**Comment by ciscoheat** [comment]
Should be working fine now with the latest alpha.

**Comment by ciscoheat** [comment]
Closing this, as tests have passed for a while.

**Comment by fehnomenal** [comment]
Sorry, I did not have a chance to try v2 yet, but great that you could solve this. Thank you for your great work!
