### ISSUE TITLE
Input validation in form action not working, returns valid when it should not.  

### ISSUE THREAD

**Issue by alexbjorlig** [ciscoheat/sveltekit-superforms#295]
I might have misunderstood what the purpose and idea of Sveltekit-superforms is - at least regarding input validation.

With this **schema**:

```
const schema = z.object({
	costEstimate: z.number()
});
```

And this input:
```
[['gitte', '234'], ['__superform_id', 'grijtr']]
```

Why is it valid? And even "worse", why is `costEstimate` suddenly 0 of all things? 

![CleanShot 2023-12-08 at 08 56 45@2x](https://github.com/ciscoheat/sveltekit-superforms/assets/9967422/0145603b-f359-46a7-bddf-09d5774b176e)

Link to stackblitz [here](https://stackblitz.com/edit/sveltejs-kit-template-default-nbtfws?file=src%2Froutes%2Fabout%2F%2Bpage.server.js).

**Comment by alexbjorlig** [comment]
> And since it wasn't posted

Wait a moment? The form was posted - with very invalid data? `costEstimate` was not even part of the `formData()`?

The implications of my stackblitz is essentially that there is no input validation on superforms at all? If I POST `[['foo', 'bar']]` to my schema above, it's still valid(!)

**Comment by ciscoheat** [comment]
The strict mode issue #217 can probably be a solution to this, so maybe an extra option can be added to `superValidate`. Need to think of how to do it best.

**Comment by ciscoheat** [comment]
It's a form library, not a strict type validation library, since all posted values are strings anyway, so you'll need some data coercion, and it's hard to make it work in every case and still keep a good DX.

Here's my line of reasoning for the current "non-strict" mode of Superforms: You will eventually have a `costEstimate` input field somewhere. Since it's a number, the type should also be `number` for the field. The default value for `<input type="number">` is `0`. Hence, zero will be posted, correlating with the default type. Which also correlates to the schema, which sets no `min` constraint on the value.

There's been no complaints up until this point, so I think most people are fine with how it works right now. I will take a look at the strict mode though, or maybe you can help out with a PR?
