### ISSUE TITLE
Feature request: Add form attributes to server API

### ISSUE THREAD

**Issue by coryvirok** [ciscoheat/sveltekit-superforms#36]
It would be convenient to be able to do something like this:

```ts
// +page.server.ts
const fooForm = await superValidate(event, schema, { id: 'fooForm', action: '?/foo'})
const barForm = await superValidate(event, schema, { id: 'barForm', action: '?/bar', method: 'GET'})
// ...
```

```svelte
<!-- +page.svelte -->
<form {...$fooForm.formAttrs}>
  <!-- fields -->
</form>
```

Primarily, I'm interested in passing along the `action` attribute from server to client. This is useful in case the action URL changes. In that case, it would only need to be updated on the server-side and not in the `.svelte` code as well.

---

Also, I just started using this lib and I'm liking it so far. Thank you!

**Comment by ciscoheat** [comment]
Hi, glad you like the library! I think that can be implemented as an attributes option:

```ts
const fooForm = await superValidate(event, schema, {
  attributes: { id: 'fooForm', action: '?/foo'}
})
```

And used in the page:

```svelte
<script lang="ts">
  const { form, attributes, ... } = superForm(data.form)
</script>

<form {...$attributes}>
```

There is a source of duplication though, since you need to pass the attributes in the form actions as well, unless `undefined` should mean "no change" (which it doesn't in the rest of the API). Any thoughts about this?

**Comment by ciscoheat** [comment]
Will be added by popular request.

**Comment by ciscoheat** [comment]
Closing this, let's keep discussing in #206.
