### ISSUE TITLE
💡 ideas for improved DX

### ISSUE THREAD

**Issue by paoloricciuti** [ciscoheat/sveltekit-superforms#8]
Hey I was reading a bit of the documentation. First thing first this library seems great and I can't wait to try it out.

While I was reading tho I had some ideas on how to improve the developer experience and if you are ok with it I can even give you a hand developing this changes.

Basically the main pain point I see is that I have to remember to always return the form object. Also I always have to pass the event to the superValidate function. And on the .svelte side I have to remember to pass data.form to superForm.

I think all of this can be avoided. How? Just make superValidate an higher order function that takes in the actual load/action function do his things and than calls the actual load function. I did something similar for sveltekit-defer.

```ts
//+page.server.ts

export const load = superValidate(schema, (event, form)=>{
    // Here the user can just do whatever he wants and
    // Return whatever he wants. He also has access to form, the current return value of superValidate
});
```

Under the hood you will do something like this

```ts
export function superValidate(schema, load){
    return (event)=>{
        //Do your thing here, you have access to schema and event
        const returnVal = await load();
        return {
            ...returnVal,
            form, //here you return form so that the user doesn't have to
        }
    }
}
```

On the .svelte side you can avoid let the user pass in data.form because in the store you have access to $page which contains $page.data which basically the same of data. So they can call the store simply by doing.

```ts
const form = superForm();
```

And under the hood you access the form through $page.data.form (I know it's not recommended in the sveltekit documentation because than you are tied to sveltekit...but this library already is tied to sveltekit so we might just smooth the DX).

Obviously the same thing is valid for the actions, the user can simply wrap them with the superValidate HOC and you could even auto-throw the fail if the form is not valid.

**Comment by ciscoheat** [comment]
Hi, thank you for your ideas! I'm doing the same higher order load function on [sveltekit-flash-message](https://github.com/ciscoheat/sveltekit-flash-message#2-add-a-load-function-to-a-top-level-page-or-layout-server-route), but it's mostly hidden since it's layout related.

The reason I'm not using it here is that it's just as common to load data from the database into `superValidate` as to pass `null` or, as in the examples, an empty `RequestEvent` into it. So the code frequently looks like this:

```ts
export const load = (async (event) => {
  const user = await db.users.findUnique(event.params.id);
  const form = await superValidate(user, schema);
  return { form };
}) satisfies PageServerLoad;
```

...which kind of makes the HOC wrapping redundant for load functions. It's hard to explain in a brief introduction, but I'll try to improve the documentation to make it more obvious. A docosaurus site is under construction!

The form actions however is much more suitable for that. I wonder if it's possible to use the same function call for both. I'd like to keep the API minimal, imo it's better to learn one library-related thing (`return { form }`) instead of having to remember multiple function calls and their signatures, as long as the functionality is the same, of course. Especially deviating from the SvelteKit default signature is something I'd like to avoid. But I'll make some experiments!

Keeping things explicit is also something I find useful, so on the client-side, a call to `superForm` with no arguments could be confusing. Perhaps it's better to know where exactly the data is coming from. And if you're using `$page.data.form` I don't think you'll get the type information, hence the intellisense won't work for the form data, so that would be problematic in any case.
